### ISSUE TITLE
Multiple Polyline is not working

### ISSUE THREAD

**Issue by jiteshgupta1995** [mjanda/ember-leaflet-multi-options-polyline#2]
I am trying to plot a path using multiple lat and long something like demonstrated here [Ember leaflet Multi option polyline](http://hgoebl.github.io/Leaflet.MultiOptionsPolyline/demo/). I have also gone through the docs for [Adding layers](http://www.ember-leaflet.com/docs/adding-layers) but unable to make it look like Ember leaflet Multi option polyline Demo mentioned in the above link.
I am getting Error as 

> ember.debug.js:17636 TypeError: Bind must be called on a function

Is there any way to make it work?

**Comment by mjanda** [comment]
I've answered in ember-leaflet issue. I'm sorry for late reply, I'm a bit busy atm.

**Comment by jiteshgupta1995** [comment]
Hi @mjanda Thanks for Reply, I am getting error while using the code you mentioned in Ember leaflet as

> TypeError: Bind must be called on a function
    at bind (<anonymous>)

Can you create a quick Ember twiddle to help me understand what I am doing wrong. **Thanks**
